# Generated by Django 3.0 on 2023-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
